apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        #TODO: Replace this image with your own custom build if you want
        image: kafkacubeimages.azurecr.io/kafka_yahoo_manager
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zookeeper.kafka:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
      #TODO: Activate if you are working with private registry
      #imagePullSecrets:
      #  - name: "containerregistrysecret"