apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: zoo
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: zookeeper
      storage: ephemeral
  serviceName: "zoo"
  replicas: 2
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: zookeeper
        storage: ephemeral
      annotations:
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-config
        #TODO: Replace this image with your own custom build if you want
        image: kafkacubeimages.azurecr.io/kafka_init_utils
        command: ['/bin/bash', '/etc/kafka-configmap/init.sh']
        env:
        - name: ID_OFFSET
          value: "4"
        volumeMounts:
        - name: configmap
          mountPath: /etc/kafka-configmap
        - name: config
          mountPath: /etc/kafka
        - name: data
          mountPath: /var/lib/zookeeper/data
      containers:
      - name: zookeeper
        #TODO: Replace this image with your own custom build if you want
        image: kafkacubeimages.azurecr.io/kafka_alpine
        env:
        - name: KAFKA_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/kafka/log4j.properties
        command:
        - ./bin/zookeeper-server-start.sh
        - /etc/kafka/zookeeper.properties
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 -q 1 127.0.0.1 2181)" ]'
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
        - name: data
          mountPath: /var/lib/zookeeper/data
      #TODO: Reactivate if you want to use your own custom registry
      #imagePullSecrets:
      #- name: "containerregistrysecret"
      volumes:
      - name: configmap
        configMap:
          name: zookeeper-config
      - name: config
        emptyDir: {}
      - name: data
        emptyDir: {}