apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-zookeeper
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  kind: "Managed"
  storageaccounttype: Standard_LRS